
export const questions = [
    {
        question: "What is Durga Puja Art?",
        "ans": "Durga puja is bengal’s biggest festival that takes place over a week or so in september-october, on dates varying every year but announced well in advance. at the centre of the celebration is the figure of goddess durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon mahishasura. it is particularly in the streets of kolkata (calcutta), the capital of the state, that durga puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded Art show. the idols and structures created from months in advance in street corners – become exquisite works of artistic expression, unique to each locality every year. thus there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. every autumn, the entire city wakes up to an explosion of creativity, with every neighbourhood decked up in unique templates that are a mélange of traditional Art and contemporary concepts, that are diverse and creative enough to rival any international Art biennale. "
    },
    {
        question: "What is massArt",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "How did suddenly kolkata durga puja Art come in the national and international limelight?",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "Why durga puja Art is the world's biggest public Art festival ?",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "What is preview show of durga puja Art (psdpa)?",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "What is the main objective behind psdpa ?",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "What is the viewing process of psdpa ?",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "What are the most unique features of this durga puja Art of Kolkata ?",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    },
    {
        question: "What shall be accommodation & traveling plan during stay and visit",
        ans: "Durga Puja is Bengal’s biggest festival that takes place over a week or so in September-October, on dates varying every year but announced well in advance. At the center of the celebration is the figure of Goddess Durga, crafted traditionally in clay, who is worshipped in the act of vanquishing the demon Mahishasura. It is particularly in the streets of Kolkata (Calcutta), the capital of the state, that Durga Puja transcends religious bounds and serves as the cradle for the world’s largest publicly funded art show. The idols and structures created months in advance in street corners become exquisite works of artistic expression, unique to each locality every year. Thus, there is a different artistic interpretation offered in every locality through the choice of a different theme to which the entire structure conforms. Every autumn, the entire city wakes up to an explosion of creativity, with every neighborhood decked up in unique templates that are a mélange of traditional art and contemporary concepts, diverse and creative enough to rival any international art biennale."
    }
];
